FROM node:17-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG VITE_AWS_REGION
ARG VITE_AWS_ACCESS_KEY_ID
ARG VITE_AWS_SECRET_ACCESS_KEY
ARG VITE_API_GATEWAY_URL
ENV VITE_AWS_REGION=$VITE_AWS_REGION
ENV VITE_AWS_ACCESS_KEY_ID=$VITE_AWS_ACCESS_KEY_ID
ENV VITE_AWS_SECRET_ACCESS_KEY=$VITE_AWS_SECRET_ACCESS_KEY
ENV VITE_API_GATEWAY_URL=$VITE_API_GATEWAY_URL
CMD ["npm", "run", "dev"]